[package]
name = "feedyourai"
version = "1.7.2"
edition = "2024"
description = "A tool to combine text files for AI processing with flexible filtering options."
authors = ["atrtde"]
homepage = "https://github.com/atrtde/feedyourai"
repository = "https://github.com/atrtde/feedyourai"
documentation = "https://github.com/atrtde/feedyourai"
exclude = ["assets/*", ".github/*"]
license = "MIT"

[[bin]]
name = "fyai"
path = "src/main.rs"

[dependencies]
clap = "4.5.59"
arboard = "3.6.1"
dirs = "6.0.0"
ignore = "0.4.25"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
walkdir = "2.5.0"
tempfile = "3.25.0"
thiserror = "2.0.18"
anyhow = "1.0.101"
